name = 'bemiraculous'
type = 'webpack'
account_id = '1fba8691d45f3422a3e3a44d1b1e4dab'
usage_model = ''
workers_dev = true

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
