name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install
      - name: Build script
        run: |
          npm run build
          printf "\n\n"
          cat dist/*.js
          printf "\n\n"
          rm -rf dist
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiKey: ${{ secrets.CF_API_KEY }}
          email: ${{ secrets.CF_EMAIL }}
